### ISSUE TITLE
Error when sending the sliced print to the Qidi X-MAX printer

### ISSUE THREAD

**Issue by DarkDvr** [nkuvyrkin/Ultimaker-Cura-v5.x-QIDI-Printer-Plugin#4]
This plugin is something I'm really excited about.
So the error I'm getting is when clicking the "Send to XMAX@x-max" button to send the print to the printer, I get a Crash Report from Cura. Attaching the screenshot and the traceback/log from the error message.

-----------

`Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Roaming\cura\5.2\plugins\QidiPrint\QidiPrintOutputDevice.py", line 322, in onFilenameAccepted
    success = writer.write(fp, None, MeshWriter.OutputMode.TextMode)
  File "cura\Utils\Threading.py", line 31, in _call_on_qt_thread_wrapper
    return func(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Roaming\cura\5.2\plugins\QidiPrint\ChituCodeWriter.py", line 66, in write
    result=self.modify(gcode_textio.getvalue())
  File "C:\Users\Andrew\AppData\Roaming\cura\5.2\plugins\QidiPrint\ChituCodeWriter.py", line 73, in modify
    temp_in_data=self.generate_image_code(self._snapshot)
  File "C:\Users\Andrew\AppData\Roaming\cura\5.2\plugins\QidiPrint\ChituCodeWriter.py", line 107, in generate_image_code
    width = image.width()
AttributeError: 'NoneType' object has no attribute 'width'
`

-------
`Thread 0x00001a80 (most recent call first):
  File "C:\Program Files\Ultimaker Cura\share\cura\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 88 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004278 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000b70 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "C:\Program Files\Ultimaker Cura\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004074 (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004b7c (most recent call first):
  File "C:\Program Files\Ultimaker Cura\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002ea0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000008ec (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000b34 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002f18 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001a3c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003420 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000443c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000018d4 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x00000dd4 (most recent call first):
  File "cura\CrashHandler.py", line 397 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 165 in exceptHook
  File "UM\Qt\QtApplication.py", line 416 in exec
  File "cura\CuraApplication.py", line 897 in run
  File "cura_app.py", line 239 in <module>
`
![Screenshot_2](https://user-images.githubusercontent.com/1627943/196770420-13fb4598-242f-446c-ac1b-501259bbb097.jpg)

**Comment by nkuvyrkin** [comment]
Could you please provide me with the model you print? It seems that snapshot is not correctly processed in the plugin sometimes (depends on the model that is supposed to be printed)

**Comment by DarkDvr** [comment]
Update: Installed Cura 5.1 - works fine. So something changed in terms of communicating with the printer since 5.1.

**Comment by nkuvyrkin** [comment]
Depends on the model. I've found that sometimes Cura does not returns snapshot of the model which is sent to the printer.
In such cases gcode will be sent to the printer without model picture. Please check out the fixed version https://github.com/nkuvyrkin/Ultimaker-Cura-v5.1-QIDI-X-CF-Pro-Plugin/releases/tag/v1.4.1
